package nextflow.config.scopes

import groovy.transform.CompileStatic
import nextflow.config.dsl.ConfigOption
import nextflow.config.dsl.ConfigScope

@CompileStatic
class DagConfig implements ConfigScope {

    DagConfig() {}

    @Override
    String name() {
        'dag'
    }

    @Override
    String description() {
        '''
        The `dag` scope controls the workflow diagram generated by Nextflow.

        [Read more](https://nextflow.io/docs/latest/config.html#scope-dag)
        '''
    }

    @ConfigOption('''
        When `true` enables the generation of the DAG file (default: `false`).
    ''')
    boolean enabled

    @ConfigOption('''
        *Only supported by the HTML and Mermaid renderers.*

        Controls the maximum depth at which to render sub-workflows (default: no limit).
    ''')
    int depth

    @ConfigOption('''
        *Only supported by the HTML and Mermaid renderers.*

        Controls the direction of the DAG, can be `'LR'` (left-to-right) or `'TB'` (top-to-bottom) (default: `'TB'`).
    ''')
    String direction

    @ConfigOption('''
        Graph file name (default: `'dag-<timestamp>.html'`).
    ''')
    String file

    @ConfigOption('''
        When `true` overwrites any existing DAG file with the same name (default: `false`).
    ''')
    boolean overwrite

    @ConfigOption('''
        *Only supported by the HTML and Mermaid renderers.*

        When `false`, channel names are omitted, operators are collapsed, and empty workflow inputs are removed (default: `false`).
    ''')
    boolean verbose

}
