package nextflow.config.scopes

import groovy.transform.CompileStatic
import nextflow.config.dsl.ConfigOption
import nextflow.config.dsl.ConfigScope

@CompileStatic
class TimelineConfig implements ConfigScope {

    TimelineConfig() {}

    @Override
    String name() {
        'timeline'
    }

    @Override
    String description() {
        '''
        The `timeline` scope controls the execution timeline report generated by Nextflow.

        [Read more](https://nextflow.io/docs/latest/config.html#scope-timeline)
        '''
    }

    @ConfigOption('''
        When `true` enables the generation of the timeline report file (default: `false`).
    ''')
    boolean enabled

    @ConfigOption('''
        Timeline file name (default: `'timeline-<timestamp>.html'`).
    ''')
    String file

    @ConfigOption('''
        When `true` overwrites any existing timeline file with the same name.
    ''')
    boolean overwrite

}
