/*
 * Copyright 2013-2024, Seqera Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package nextflow.config.scopes

import groovy.transform.CompileStatic
import nextflow.config.dsl.ConfigOption
import nextflow.config.dsl.ConfigScope

@CompileStatic
class TimelineConfig implements ConfigScope {

    TimelineConfig() {}

    @Override
    String name() {
        'timeline'
    }

    @Override
    String description() {
        '''
        The `timeline` scope controls the execution timeline report generated by Nextflow.

        [Read more](https://nextflow.io/docs/latest/config.html#scope-timeline)
        '''
    }

    @ConfigOption('''
        When `true` enables the generation of the timeline report file (default: `false`).
    ''')
    boolean enabled

    @ConfigOption('''
        Timeline file name (default: `'timeline-<timestamp>.html'`).
    ''')
    String file

    @ConfigOption('''
        When `true` overwrites any existing timeline file with the same name.
    ''')
    boolean overwrite

}
