package nextflow.config.scopes

import groovy.transform.CompileStatic
import nextflow.config.dsl.ConfigOption
import nextflow.config.dsl.ConfigScope

@CompileStatic
class TraceConfig implements ConfigScope {

    TraceConfig() {}

    @Override
    String name() {
        'trace'
    }

    @Override
    String description() {
        '''
        The `trace` scope controls the layout of the execution trace file generated by Nextflow.

        [Read more](https://nextflow.io/docs/latest/config.html#scope-trace)
        '''
    }

    @ConfigOption('''
        When `true`, enables the creation of the execution trace report file (default: `false`).
    ''')
    boolean enabled

    @ConfigOption('''
        Comma separated list of fields to be included in the report. The available fields are listed [here](https://nextflow.io/docs/latest/tracing.html#trace-report).
    ''')
    String fields

    @ConfigOption('''
        Trace file name (default: `'trace-<timestamp>.txt'`).
    ''')
    String file

    @ConfigOption('''
        When `true`, overwrites any existing trace file with the same name.
    ''')
    boolean overwrite

    @ConfigOption('''
        When `true`, uses raw number formatting i.e. durations are reported in milliseconds and memory in bytes.
    ''')
    boolean raw

    @ConfigOption('''
        Character used to separate values in each row (default: `\t`).
    ''')
    String sep

}
