/*
 * Copyright 2013-2024, Seqera Labs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package nextflow.config.scopes

import groovy.transform.CompileStatic
import nextflow.config.dsl.ConfigOption
import nextflow.config.dsl.ConfigScope

@CompileStatic
class TraceConfig implements ConfigScope {

    TraceConfig() {}

    @Override
    String name() {
        'trace'
    }

    @Override
    String description() {
        '''
        The `trace` scope controls the layout of the execution trace file generated by Nextflow.

        [Read more](https://nextflow.io/docs/latest/config.html#scope-trace)
        '''
    }

    @ConfigOption('''
        When `true`, enables the creation of the execution trace report file (default: `false`).
    ''')
    boolean enabled

    @ConfigOption('''
        Comma separated list of fields to be included in the report. The available fields are listed [here](https://nextflow.io/docs/latest/tracing.html#trace-report).
    ''')
    String fields

    @ConfigOption('''
        Trace file name (default: `'trace-<timestamp>.txt'`).
    ''')
    String file

    @ConfigOption('''
        When `true`, overwrites any existing trace file with the same name.
    ''')
    boolean overwrite

    @ConfigOption('''
        When `true`, uses raw number formatting i.e. durations are reported in milliseconds and memory in bytes.
    ''')
    boolean raw

    @ConfigOption('''
        Character used to separate values in each row (default: `\t`).
    ''')
    String sep

}
